### PR TITLE
Added support for ido-mode

### PR DESCRIPTION
**Pull request by xlighting**

### CODE REVIEW

**Comment by whitlockjc** [comment]
I don't see any of these colors in the Atom Dark [UI](https://github.com/atom/atom-dark-ui) or [Syntax](https://github.com/atom/atom-dark-syntax) projects.  Is this for Atom One Dark by chance?

**Comment by xlighting** [comment]
The stuff i added is just for ido-mode in emacs, I think it is harmonious with atom-dark-theme-emacs in emacs ,thought the colors are not in the Atom Dark UI or Syntax projects.

**Comment by whitlockjc** [comment]
I realize it's just for ido-mode but I would had expected you'd use colors from the Atom Dark palette.  Do you mind attaching a screenshot, or a few, that show the look of this?  I'll likely merge it but I'd love to see what it looks like.  I don't use ido-mode...but I guess I could start.

**Comment by xlighting** [comment]
# The stuff I added

;; ido-mode
'(ido-first-match ((t (:foreground "#C678DD" :weight bold))))
'(ido-only-match ((t (:foreground "#E06C75" :weight bold))))
 '(ido-subdir ((t (:foreground "#61AFEF"))))
 '(ido-virtual ((t (:foreground "#5C6370"))))

# The  original  look :

## ido-first-match ( bold gray) and -ido-subdir (red)

origin

## ido-only-match

only-match

## ido-virtual

virtual-buffers

# New look:

## ido-first-match and -ido-subdir

new

## ido-only-match

new-only-match

## ido-virtual

new-virtual

**Comment by whitlockjc** [comment]
Very nice.  Thank you so much.  Let me look at the colors once more to see where we're doing these elsewhere and modify one or the other for consistency.  I mean, we have the pale blue and orange used elsewhere but your hex values are different than mine.

**Comment by whitlockjc** [comment]
What happened?  I was planning to merge it.

**Comment by xlighting** [comment]
My colors breakes the consistency

**Comment by whitlockjc** [comment]
I'd love the contribution if you want to correct the colors.  Should had been a simple fix.

**Comment by whitlockjc** [comment]
I can do it for you if you'd rather.  I don't mind.

**Pull request closed without merging**
